server:
  port: 8082
  servlet:
    context-path: /encyclopedia-service

spring:
  application:
    name: EncyclopediaSearch
  config:
    import: optional:config/application-secret.yml

naver:
  api:
    base-url: https://openapi.naver.com/v1/search
    client-id: X56LS44My6N59TADrp8f
    client-secret: zfpsGIXmdf
    default-display: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info