server:
  port: 8081
  servlet:
    context-path: /encyc-service

spring:
  application:
    name=EncyclopediaSearch
  config:
    import: optional:config/application-secret.yml

naver:
  api:
    base-url: https://openapi.naver.com/v1/search
    client-id: ${naver.api.client-id}
    client-secret: ${naver.api.client-secret}
    default-display: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info